// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func SearchInterface(authenticated bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>What-A-Git-Year - Home</title><script src=\"https://cdn.jsdelivr.net/npm/htmx.org@2.0.7/dist/htmx.min.js\"></script><link href=\"https://cdn.jsdelivr.net/npm/daisyui@5\" rel=\"stylesheet\" type=\"text/css\"><script src=\"https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4\"></script><script defer src=\"https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js\"></script></head><body class=\"min-h-screen bg-base-100 flex flex-col\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = NavBar(authenticated).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"flex-1 flex items-center justify-center p-4\"><div class=\"w-full max-w-2xl\"><div class=\"text-center mb-12\"><h1 class=\"text-6xl font-bold mb-4 tracking-tight\"><span class=\"text-base-content\">What</span> <span class=\"text-primary\">-A-</span> <span class=\"text-base-content\">Git</span> <span class=\"text-primary\">-</span> <span class=\"text-base-content\">Year</span></h1><p class=\"text-base-content/60 text-lg\">Discover the treasures in your GitHub journey!</p></div><div class=\"flex flex-col items-center mb-8\"><img src=\"/static/search.png\" class=\"w-[50%] h-[50%]\"></div><!-- Search Form --><div class=\"card bg-base-200 shadow-2xl\"><div class=\"card-body p-8\"><form id=\"search-form\" class=\"space-y-6\"><!-- Search Type Toggle --><div class=\"flex justify-center gap-2\"><input type=\"radio\" name=\"search-type\" value=\"user\" id=\"type-user\" class=\"radio radio-primary radio-sm\" checked> <label for=\"type-user\" class=\"label-text cursor-pointer mr-6\">User</label> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if authenticated {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<input type=\"radio\" name=\"search-type\" value=\"org\" id=\"type-org\" class=\"radio radio-primary radio-sm\"> <label for=\"type-org\" class=\"label-text cursor-pointer\">Organization</label>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<input type=\"radio\" name=\"search-type\" value=\"org\" id=\"type-org\" class=\"radio radio-primary radio-sm\" disabled> <label for=\"type-org\" class=\"label-text cursor-pointer text-gray-500\">Organization (log in for this feature)</label>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><div class=\"form-control\"><div class=\"join w-full\"><input type=\"text\" id=\"search-input\" placeholder=\"Enter GitHub username or organization...\" class=\"input input-bordered input-lg join-item w-full focus:outline-offset-0\" required> <button type=\"submit\" class=\"btn btn-primary btn-lg join-item px-8\"><svg xmlns=\"http://www.w3.org/2000/svg\" class=\"h-6 w-6\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z\"></path></svg></button></div></div><!-- Popular Examples --><div class=\"text-center\"><p class=\"text-sm text-base-content/40 mb-2\">Try:</p><div class=\"flex flex-wrap justify-center gap-2\"><button type=\"button\" class=\"badge badge-outline badge-lg cursor-pointer hover:badge-primary transition-colors\" onclick=\"document.getElementById('search-input').value = 'torvalds'\">torvalds</button> <button type=\"button\" class=\"badge badge-outline badge-lg cursor-pointer hover:badge-primary transition-colors\" onclick=\"document.getElementById('search-input').value = 'google'\">google</button> <button type=\"button\" class=\"badge badge-outline badge-lg cursor-pointer hover:badge-primary transition-colors\" onclick=\"document.getElementById('search-input').value = 'huggingface'\">huggingface</button></div></div></form></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Footer().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
