// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package cacheutils

import (
	"database/sql"
)

type Cached struct {
	ID              int64
	K               string
	User            string
	Repositories    int64
	Commits         int64
	Stars           int64
	Forks           int64
	AvatarUrl       string
	TopRepositories sql.NullString
	Topics          sql.NullString
	CreatedAt       sql.NullTime
}
