// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.cache.sql

package cacheutils

import (
	"context"
	"database/sql"
)

const cleanCache = `-- name: CleanCache :exec
DELETE FROM cached
WHERE datetime(created_at) < datetime('now', '-1 hour')
`

func (q *Queries) CleanCache(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanCache)
	return err
}

const cleanCacheTest = `-- name: CleanCacheTest :exec
DELETE FROM cached
WHERE datetime(created_at) < datetime('now', '-1 second')
`

func (q *Queries) CleanCacheTest(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanCacheTest)
	return err
}

const getStatsByKey = `-- name: GetStatsByKey :one
SELECT id, k, user, repositories, commits, stars, forks, avatar_url, top_repositories, topics, created_at
FROM cached
WHERE k = ?
AND datetime(created_at) >= datetime('now', '-1 hour')
`

func (q *Queries) GetStatsByKey(ctx context.Context, k string) (Cached, error) {
	row := q.db.QueryRowContext(ctx, getStatsByKey, k)
	var i Cached
	err := row.Scan(
		&i.ID,
		&i.K,
		&i.User,
		&i.Repositories,
		&i.Commits,
		&i.Stars,
		&i.Forks,
		&i.AvatarUrl,
		&i.TopRepositories,
		&i.Topics,
		&i.CreatedAt,
	)
	return i, err
}

const setStats = `-- name: SetStats :one
INSERT INTO cached (k, user, stars, repositories, commits, forks, top_repositories, topics, avatar_url)
VALUES (?,?,?,?,?,?,?,?,?)
RETURNING id, k, user, repositories, commits, stars, forks, avatar_url, top_repositories, topics, created_at
`

type SetStatsParams struct {
	K               string
	User            string
	Stars           int64
	Repositories    int64
	Commits         int64
	Forks           int64
	TopRepositories sql.NullString
	Topics          sql.NullString
	AvatarUrl       string
}

func (q *Queries) SetStats(ctx context.Context, arg SetStatsParams) (Cached, error) {
	row := q.db.QueryRowContext(ctx, setStats,
		arg.K,
		arg.User,
		arg.Stars,
		arg.Repositories,
		arg.Commits,
		arg.Forks,
		arg.TopRepositories,
		arg.Topics,
		arg.AvatarUrl,
	)
	var i Cached
	err := row.Scan(
		&i.ID,
		&i.K,
		&i.User,
		&i.Repositories,
		&i.Commits,
		&i.Stars,
		&i.Forks,
		&i.AvatarUrl,
		&i.TopRepositories,
		&i.Topics,
		&i.CreatedAt,
	)
	return i, err
}
